# Generated by Django 4.2.13 on 2026-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre de la Red"),
                ),
                ("url", models.URLField(verbose_name="URL del Perfil")),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Ejemplo: fa-brands fa-x-twitter, fa-brands fa-facebook-f, fa-brands fa-instagram, fa-brands fa-linkedin-in",
                        max_length=50,
                        verbose_name="Clase del Icono FontAwesome",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
                "ordering": ["order", "name"],
            },
        ),
    ]
