# Generated by Django 4.2.13 on 2026-06-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Historia",
                "verbose_name_plural": "Historias",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(
                default="Anónimo", max_length=100, verbose_name="Nombre del autor"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Comentario"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="stories.story",
                verbose_name="Historia",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.TextField(verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="story",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Descripción corta para vista previa",
                verbose_name="Resumen",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="extraction_error",
            field=models.TextField(blank=True, verbose_name="Error de extracción"),
        ),
        migrations.AlterField(
            model_name="story",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado de extracción de IA",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publicado el"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("archived", "Archivado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="stories.category",
                verbose_name="Categoría",
            ),
        ),
    ]
