# Generated by Django 4.2.13 on 2026-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_category_alter_comment_options_alter_story_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Título del Banner"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/",
                        verbose_name="Imagen del Banner (Local)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Usa esto si prefieres una URL externa de imagen en lugar de subir un archivo",
                        verbose_name="URL de Imagen (Alternativa)",
                    ),
                ),
                ("link_url", models.URLField(verbose_name="Enlace de Destino")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("arriba", "Arriba (Cabecera)"),
                            ("abajo", "Abajo (Pie de página)"),
                            ("lateral", "Lateral (Barra lateral)"),
                            ("entre_historias", "Entre Historias (Feed)"),
                        ],
                        max_length=20,
                        verbose_name="Posición",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
            ],
            options={
                "verbose_name": "Banner de Publicidad",
                "verbose_name_plural": "Banners de Publicidad",
            },
        ),
    ]
