# Generated by Django 4.2.13 on 2026-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(
                blank=True,
                default="Anónimo",
                max_length=100,
                verbose_name="Nombre del autor",
            ),
        ),
    ]
