# Generated by Django 4.2.13 on 2026-06-10 18:51

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_alter_comment_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Dirección IP"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Aprobado"),
        ),
        migrations.AddField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stories/covers/",
                verbose_name="Imagen de portada",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora para publicar automáticamente (solo si el estado es 'Programado')",
                null=True,
                verbose_name="Publicación programada",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(max_length=100, verbose_name="Nombre del autor"),
        ),
        migrations.AlterField(
            model_name="story",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("scheduled", "Programado"),
                    ("archived", "Archivado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_approved"], name="stories_com_is_appr_99746a_idx"
            ),
        ),
    ]
