# Generated by Django 4.2.13 on 2026-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_comment_ip_address_comment_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="html_code",
            field=models.TextField(
                blank=True,
                help_text="Usa esto para inyectar código personalizado (AdSense, iFrames, scripts, etc.) en lugar de usar imagen y enlace",
                verbose_name="Código HTML del Banner",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace de Destino"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[
                    ("arriba", "Arriba (Cabecera)"),
                    ("abajo", "Abajo (Pie de página)"),
                    ("lateral", "Lateral (Barra lateral)"),
                    ("entre_historias", "Entre Historias (Feed)"),
                ],
                help_text="Tamaños recomendados:<br>• Arriba: 728x90px o 970x90px<br>• Abajo: 728x90px<br>• Lateral: 300x250px o 300x600px<br>• Entre Historias: 728x90px o 300x250px",
                max_length=20,
                verbose_name="Posición",
            ),
        ),
    ]
