# Generated by Django 4.2.13 on 2026-06-11 18:49

import apps.stories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_banner_html_code_alter_banner_link_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banners/",
                validators=[apps.stories.validators.validate_image_size_and_dimensions],
                verbose_name="Imagen del Banner (Local)",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stories/covers/",
                validators=[apps.stories.validators.validate_image_size_and_dimensions],
                verbose_name="Imagen de portada",
            ),
        ),
    ]
