# Generated by Django 4.2.13 on 2026-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0008_alter_banner_image_alter_story_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="audio_error",
            field=models.TextField(
                blank=True, verbose_name="Error de generación de audio"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="stories/audio/",
                verbose_name="Archivo de audio",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="audio_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado de generación de audio",
            ),
        ),
    ]
