# Generated by Django 4.2.13 on 2026-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0009_story_audio_error_story_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="audio_voice",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Voz TTS utilizada para sintetizar el audio (ef_dora, em_alex)",
                max_length=30,
                verbose_name="Voz del narrador",
            ),
        ),
    ]
