# Generated by Django 4.2.13 on 2026-06-10 18:51

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenido"),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="Resumen corto")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/covers/",
                        verbose_name="Imagen de portada",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="fa-solid fa-file-lines",
                        help_text="Clase CSS del icono de FontAwesome (ej. fa-solid fa-user, fa-solid fa-book)",
                        max_length=100,
                        verbose_name="Icono FontAwesome",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "show_in_navbar",
                    models.BooleanField(default=True, verbose_name="Mostrar en navbar"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Menor número = aparece primero",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Página Personal",
                "verbose_name_plural": "Páginas Personales",
                "ordering": ["order", "title"],
            },
        ),
    ]
