# Generated by Django 4.2.13 on 2026-06-11 18:49

import apps.stories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pages/covers/",
                validators=[apps.stories.validators.validate_image_size_and_dimensions],
                verbose_name="Imagen de portada",
            ),
        ),
    ]
