# Generated by Django 4.2.13 on 2026-06-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extractions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("generated_text", models.TextField()),
                (
                    "user_edited_text",
                    models.TextField(blank=True, help_text="User's edited version"),
                ),
                ("hashtags", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_url", models.URLField(blank=True)),
                (
                    "published_id",
                    models.CharField(
                        blank=True,
                        help_text="Platform-specific post ID",
                        max_length=255,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to="extractions.textextraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("extraction", "platform")},
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "unique_together": {("user", "platform")},
            },
        ),
    ]
