# Generated by Django 4.2.13 on 2026-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("accepted", "Accepted"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
